#!/bin/fish

# USAGE: ./start        for application start
#        ./start --s    for shell start

#        ./data directory gets mounted as /home/data

# CD to current folder
set DIR (cd (dirname (status -f)); and pwd)

function error
  echo "Usage: start (--s | --shell)"
  echo "-s Shell only"
  exit 1
end

set -l options (fish_opt -s s -l shell)
argparse $options -- $argv

if test "$_flag_s" = "--shell"
  docker run -it --network=host --env DISPLAY=$DISPLAY --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD/data:/home/data itsec /bin/bash
else
  docker run -it --network=host --env DISPLAY=$DISPLAY --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD/data:/home/data itsec /bin/bash -c "cd insecurity-refactoring/InsecurityRefactoring && ./start.sh"
end
