#!/bin/bash

# USAGE: ./start        for application start
#        ./start --s    for shell start

#        ./data directory gets mounted as /home/data

# CD to script directory
cd "$(dirname "$0")"

if [ $# -eq 0 ]; then
   docker run -it --network=host --env DISPLAY=$DISPLAY --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD/data:/home/data itsec /bin/bash -c "cd insecurity-refactoring/InsecurityRefactoring && ./start.sh";
   exit 0;
fi

if [ "$1" == "-s" ]; then
  docker run -it --network=host --env DISPLAY=$DISPLAY --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD/data:/home/data itsec /bin/bash;
  exit 0;
fi

echo "Usage: ./start (-s)"
echo "-s Shell only"
exit 1
